# Generated by Django 5.2.2 on 2025-06-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['post_type', 'display_order'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리들'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='display_order',
        ),
    ]
