# Generated by Django 5.2.2 on 2025-06-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community_api_service", "0003_alter_category_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "permissions": [
                    ("can_manage_posts", "게시물 관리 권한"),
                    ("can_delete_posts", "게시물 삭제 권한"),
                ],
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물들",
            },
        ),
    ]
